export interface Message {
  id: string;
  role: 'user' | 'model';
  text: string;
  image?: string; // Base64 string
  timestamp: number;
  isAudio?: boolean;
}

export interface Topic {
  id: string;
  title: string;
  lastUpdated: number;
  messages: Record<string, {
    q: string;
    a: string;
    time: number;
    img?: string; // Optional image sent by user
    genImg?: string; // Optional image generated by AI
  }>;
}

export interface UserProfile {
  uid: string;
  email: string;
  isPremium: boolean;
}

export interface AppSettings {
  darkMode: boolean;
  personality: 'friendly' | 'professional' | 'creative';
}

export interface UsageLimits {
  messages: number;
  images: number;
  uploads: number;
  date: string; // ISO Date string YYYY-MM-DD
}

export const LIMITS = {
  MESSAGES: 100,
  IMAGES: 7,
  UPLOADS: 5
};